In [ ]:
import requests
import pandas as pd
from pandas import DataFrame 
%matplotlib inline
import matplotlib.pyplot as plt
import zipfile
import numpy as np
import io
import time
from numpy import nan
from pprint import pprint 
print("Import Successful")
#!wget https://www150.statcan.gc.ca/n1/tbl/csv/10100084-eng.zip
#!unzip 10100084-eng.zip

Import Successful


# Downloading the data

In [ ]:



df = pd.read_csv("TorontoListings.csv")


# Data Cleaning

In [ ]:
df.describe()

id  ...  availability_365
count  1.874600e+04  ...      18746.000000
mean   2.673976e+07  ...        125.690761
std    1.298332e+07  ...        136.844548
min    1.419000e+03  ...          0.000000
25%    1.634553e+07  ...          0.000000
50%    2.775978e+07  ...         83.000000
75%    3.853432e+07  ...        252.000000
max    4.578971e+07  ...        365.000000

[8 rows x 11 columns]

From above, We can see there is a column which is empty, Hence, We drop empty, NAN data from the set. 

In [ ]:

df.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group               float64
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

Since id and host_name, both are giving the same information, We keep one of them and We will do the same thing for name and coordination(lattitude+longitude), We will concatenate them into coulumn location

In [ ]:
df['location'] = [', '.join(str(x) for x in y) for y in map(tuple, df[['latitude', 'longitude']].values)]
df.head(20)

id  ...                                location
0    1419  ...                     43.64617, -79.42451
1    8077  ...            43.64105, -79.37628000000001
2   12604  ...                     43.66724, -79.41598
3   23691  ...  43.696020000000004, -79.45468000000001
4   26654  ...                       43.6453, -79.3894
5   27423  ...                      43.6689, -79.32592
6   28160  ...  43.703759999999996, -79.39076999999999
7   30931  ...                     43.64151, -79.37643
8   40456  ...                     43.63532, -79.44049
9   41887  ...                     43.69466, -79.28667
10  42892  ...                     43.64451, -79.38185
11  43964  ...            43.74948, -79.29146999999999
12  44452  ...                     43.67185, -79.38583
13  45399  ...                     43.65972, -79.38172
14  45601  ...                     43.66274, -79.33096
15  45893  ...                     43.67105, -79.38481
16  50110  ...                     43.66899, -79.38548
17  51616  ...           43.642959999999995, -79.40451
18  57483  ...                     43.64286, -79.38073
19  64641  ...             43.6444, -79.40829000000001

[20 rows x 17 columns]

In [ ]:
df.drop(['neighbourhood_group', 'name', 'host_name'], 1, inplace = True)
df.head()

id  host_id  ... availability_365                                location
0   1419     1565  ...                0                     43.64617, -79.42451
1   8077    22795  ...              365            43.64105, -79.37628000000001
2  12604    48239  ...                0                     43.66724, -79.41598
3  23691    93825  ...              240  43.696020000000004, -79.45468000000001
4  26654   113345  ...              295                       43.6453, -79.3894

[5 rows x 14 columns]

# taking care of missing data

In [ ]:
df = df[['id', 'host_id', 'neighbourhood', 'latitude', 'longitude', 'room_type','minimum_nights', 'number_of_reviews', 'last_review', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365', 'location', 'price']]

In [ ]:
# replace '0' values with 'nan'
df[['number_of_reviews', 'availability_365']] = df[['number_of_reviews', 'availability_365']].replace(0, nan)
# count the number of nan values in each column
print(df.isnull().sum())

id                                   0
host_id                              0
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
minimum_nights                       0
number_of_reviews                 3958
last_review                       3958
reviews_per_month                 3958
calculated_host_listings_count       0
availability_365                  6641
location                             0
price                                0
dtype: int64


In [ ]:
#conversion of the 'REF_DATE' from a string to a proper datetime object.
df['last_review'] = pd.to_datetime(df['last_review']) 
# fill missing values with mean column values
df.fillna(df.mean(), inplace=True)




/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  after removing the cwd from sys.path.


# Encoding categorical Data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
X=df.iloc[: , 5:12].values
y=df.iloc[:, 13].values
one_hot = pd.get_dummies(df['room_type'])


In [ ]:
one_hot_df = pd.concat([df, one_hot], axis=1)


In [ ]:
one_hot_df = one_hot_df[['id', 'host_id', 'neighbourhood','minimum_nights', 'number_of_reviews',
       'calculated_host_listings_count', 'availability_365', 'reviews_per_month','latitude', 'longitude','Shared room', 'Entire home/apt',
       'Hotel room', 'Private room', 'price']]


In [ ]:
#Encoding neighbourhood
one_hot = pd.get_dummies(df['neighbourhood'])


In [ ]:
merged_df = pd.concat([one_hot_df, one_hot], axis=1)


In [ ]:
merged_df["reviews_per_month"].mean()

1.2142662969974656

In [ ]:
selected_df = merged_df[merged_df['reviews_per_month'] >= 1.2] 


In [ ]:
def movecol(df, cols_to_move=[], ref_col='', place='After'):
    
    cols = df.columns.tolist()
    if place == 'After':
        seg1 = cols[:list(cols).index(ref_col) + 1]
        seg2 = cols_to_move
    if place == 'Before':
        seg1 = cols[:list(cols).index(ref_col)]
        seg2 = cols_to_move + [ref_col]
    
    seg1 = [i for i in seg1 if i not in seg2]
    seg3 = [i for i in cols if i not in seg1 + seg2]
    
    return(df[seg1 + seg2 + seg3])
selected_df = movecol(selected_df, 
             cols_to_move=['Yorkdale-Glen Park','price'], 
             ref_col='York University Heights',
             place='After')


# definig dataset for the models

In the next lines, I am going to categorize the prices as low, affordable and expensive. Then then the model willl be trained sperately on each class.10 columns were selected to start with building our model and see how it works.

In [ ]:
def priceRanker(val):
    if  val< 100:
        return 1
    elif 170 < val:
         return 2
    else :
         return 3

selected_df["categoryPrice"] = df["price"].apply(priceRanker)
   

In [ ]:
selected_df

id    host_id  ... price  categoryPrice
1          8077      22795  ...    98              1
2         12604      48239  ...    66              1
3         23691      93825  ...    70              1
9         41887     183071  ...    75              1
10        42892     187320  ...   110              3
...         ...        ...  ...   ...            ...
18741  45785334    1023135  ...    65              1
18742  45786222  371188170  ...   158              3
18743  45786961  371195218  ...    70              1
18744  45789233  304805850  ...    39              1
18745  45789708  344709977  ...    52              1

[8657 rows x 156 columns]

In [ ]:
from sklearn.model_selection import train_test_split
#define dataset
X=selected_df.iloc[: , 7:-2].values
y =selected_df.iloc[:, -1].values
#Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.6, random_state = 0)

# Decision Tree Cross Validation

For cross validation purposes, I am going to train 10% of our dataset.

now I need to define a new classifier to fit on our cross validation dataset. which I call it clf_cv

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
acc_score_DT = []
best_score_DT = (0, -1)
best_clf_DT = None
for i in range(1,21):
    clf_DT = DecisionTreeClassifier(max_depth=i,random_state=0)
    clf_DT.fit(X_train, y_train)
    y_pred_DT=clf_DT.predict(X_test)
    
    curr_acc_DT = accuracy_score(y_test, y_pred_DT)
    acc_score_DT.append((i, curr_acc_DT))
    
    if curr_acc_DT > best_score_DT[0]:
        best_score_DT = (curr_acc_DT, i)
        best_clf_DT = clf_DT

print(best_clf_DT)
acc_score_DT

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=5, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')


[(1, 0.5499518768046199),
 (2, 0.5522617901828681),
 (3, 0.5676612127045236),
 (4, 0.5745909528392685),
 (5, 0.5820981713185756),
 (6, 0.5778633301251203),
 (7, 0.5707410972088547),
 (8, 0.5717035611164581),
 (9, 0.559191530317613),
 (10, 0.5626564003849855),
 (11, 0.5580365736284889),
 (12, 0.5549566891241579),
 (13, 0.5445620789220404),
 (14, 0.5389797882579404),
 (15, 0.5439846005774783),
 (16, 0.5393647738209817),
 (17, 0.5332050048123196),
 (18, 0.5339749759384023),
 (19, 0.5332050048123196),
 (20, 0.5274302213666987)]

## Matrix of confusion for Decision Tree cross validation

In [ ]:
from sklearn.metrics import confusion_matrix
clf_DT_final = DecisionTreeClassifier(max_depth=4,random_state=0)
clf_DT_final.fit(X_train, y_train)
y_pred_DT=clf_DT_final.predict(X_test)
cm_DT = confusion_matrix(y_test, y_pred_DT)
print(cm_DT)
accuracy_score(y_test, y_pred_DT)

[[1739   23  794]
 [ 158   51  800]
 [ 374   61 1195]]


0.5745909528392685

# Random Forest Classification 


for random forest model we have to define the number of features that we are including in our model that for this case it is 147 ( total number of coulumns _ 9). 

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=1000, n_features=147,
                            n_informative=3, n_redundant=0,
                            random_state=0, shuffle=False)


#For tuning I am going to train and fit the model with a different values for max_depth.I chose a range of  3 to 20 for max_depth.

In [ ]:
acc_score_RF = []
best_score_RF = (0, -1)
best_clf_RF = None
for i in range(1,21):
    clf_RF = RandomForestClassifier(max_depth=i,random_state=0)
    clf_RF.fit(X_train, y_train)
    y_pred_RF=clf_RF.predict(X_test)
    
    curr_acc_RF = accuracy_score(y_test, y_pred_RF)
    acc_score_RF.append((i, curr_acc_RF))
    
    if curr_acc_RF > best_score_RF[0]:
        best_score_RF = (curr_acc_RF, i)
        best_clf_RF = clf_RF
print(best_clf_RF)
acc_score_RF


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=13, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)


[(1, 0.49201154956689125),
 (2, 0.5522617901828681),
 (3, 0.5541867179980751),
 (4, 0.5620789220404235),
 (5, 0.5690086621751684),
 (6, 0.5703561116458132),
 (7, 0.5749759384023099),
 (8, 0.5792107795957652),
 (9, 0.5851780558229066),
 (10, 0.5882579403272378),
 (11, 0.5942252165543792),
 (12, 0.5921077959576516),
 (13, 0.5951876804619827),
 (14, 0.5942252165543792),
 (15, 0.594995187680462),
 (16, 0.5928777670837344),
 (17, 0.5907603464870067),
 (18, 0.5934552454282964),
 (19, 0.5861405197305101),
 (20, 0.588065447545717)]

#now We need to creat a matrix of confusion for RF cross validation 

In [ ]:
clf_RF = RandomForestClassifier(max_depth=11,random_state=0)
clf_RF.fit(X_train, y_train)
y_pred_RF=clf_RF.predict(X_test)
cm_RF= confusion_matrix(y_test, y_pred_RF)
print(cm_RF)
accuracy_score(y_test, y_pred_RF)

[[2122   26  408]
 [ 363   96  550]
 [ 692   69  869]]


0.5942252165543792

# KNN Classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)


##The only difference in terms of model tuning for KNN is we are changing the number of nearest numbers for a range from 4 to 20.

In [ ]:
acc_score_knn = []
best_score_knn = (0, -1)
best_clf_knn = None
for i in range(1,21):
    neigh = KNeighborsClassifier(n_neighbors=i)
    neigh.fit(X_train, y_train)
    y_pred_knn=neigh.predict(X_test) 
  
  
    
    curr_acc_knn = accuracy_score(y_test, y_pred_knn)
    acc_score_knn.append((i, curr_acc_knn))
    
    if curr_acc_knn > best_score_knn[0]:
        best_score_knn = (curr_acc_knn, i)
        best_clf_knn = neigh
print(best_clf_knn)
acc_score_knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=19, p=2,
                     weights='uniform')


[(1, 0.5158806544754572),
 (2, 0.5251203079884504),
 (3, 0.5393647738209817),
 (4, 0.5457170356111646),
 (5, 0.5541867179980751),
 (6, 0.5624639076034649),
 (7, 0.5572666025024061),
 (8, 0.5692011549566891),
 (9, 0.5659287776708374),
 (10, 0.5682386910490856),
 (11, 0.5674687199230029),
 (12, 0.5722810394610202),
 (13, 0.5749759384023099),
 (14, 0.5709335899903754),
 (15, 0.5718960538979788),
 (16, 0.5728585178055823),
 (17, 0.5728585178055823),
 (18, 0.5757459095283927),
 (19, 0.5794032723772858),
 (20, 0.5770933589990376)]

##now its time for the KNN_CV matrix of confusion 

In [ ]:
neigh = KNeighborsClassifier(n_neighbors=20)
neigh.fit(X_train, y_train)
y_pred_knn=neigh.predict(X_test) 
cm_knn= confusion_matrix(y_test, y_pred_knn)
print(cm_knn)
accuracy_score(y_test, y_pred_knn)

[[1891   99  566]
 [ 320  185  504]
 [ 559  149  922]]


0.5770933589990376

# #SMOTE FOR Random Forest

In [ ]:
!pip install  imbalanced-learn
from imblearn.over_sampling import SMOTE
sm = SMOTE()
X_train_res, y_train_res = sm.fit_sample(X_train, y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
acc_score_RF_res = []
best_score_RF_res = (0, -1)
best_clf_RF_res = None
for i in range(100,110):
    clf_RF_res = RandomForestClassifier(max_depth=i,random_state=0)
    clf_RF_res.fit(X_train_res, y_train_res)
    y_pred_RF_res=clf_RF_res.predict(X_test)
    
    curr_acc_RF_res = accuracy_score(y_test, y_pred_RF_res)
    acc_score_RF_res.append((i, curr_acc_RF_res))
    
    if curr_acc_RF_res > best_score_RF_res[0]:
        best_score_RF_res = (curr_acc_RF_res, i)
        best_clf_RF_res = clf_RF_res
print(best_clf_RF_res)
acc_score_RF_res


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=100, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)


[(100, 0.558614051973051),
 (101, 0.5570741097208854),
 (102, 0.5557266602502406),
 (103, 0.5570741097208854),
 (104, 0.5570741097208854),
 (105, 0.5572666025024061),
 (106, 0.5568816169393648),
 (107, 0.5578440808469682),
 (108, 0.5580365736284889),
 (109, 0.5572666025024061)]

In [ ]:
clf_RF_res = RandomForestClassifier(max_depth=19,random_state=0)
clf_RF_res.fit(X_train_res, y_train_res)
y_pred_RF_res=clf_RF_res.predict(X_test)
cm_RF_res= confusion_matrix(y_test, y_pred_RF_res)
print(cm_RF_res)
accuracy_score(y_test, y_pred_RF_res)

[[1795  323  438]
 [ 151  477  381]
 [ 382  494  754]]


0.5824831568816169

# Random Forest Model

In [ ]:

prediction_RFdict = {"y_pred":y_pred_RF_res, "y_test":y_test}
predictions_RFdf = pd.DataFrame(prediction_RFdict)
print(predictions_RFdf) 



      y_pred  y_test
0          2       3
1          3       3
2          3       1
3          1       1
4          1       1
...      ...     ...
5190       2       3
5191       1       1
5192       1       1
5193       1       1
5194       1       1

[5195 rows x 2 columns]


In [ ]:
print(RF.feature_importances_)

[1.43745681e-01 2.70312309e-01 2.69009963e-01 1.66488467e-03
 1.72187207e-01 1.73098136e-03 1.42130703e-03 2.32186524e-04
 1.06630369e-03 2.17050320e-04 2.49235714e-03 2.76579231e-03
 1.25016981e-03 3.86159951e-03 8.03726105e-04 1.09248589e-04
 6.89962331e-04 2.01753864e-04 8.99188161e-04 1.24744864e-03
 2.77584747e-04 9.18687458e-04 5.06798924e-04 4.44299685e-04
 3.05172007e-04 1.94190247e-04 1.13048925e-03 0.00000000e+00
 6.61270130e-04 6.43169332e-04 3.45902525e-03 3.27357586e-04
 1.64492738e-03 2.04116660e-04 8.72197179e-04 5.67883395e-04
 6.55930129e-04 5.80433713e-04 9.28262614e-04 1.61713487e-03
 1.48916594e-03 1.11470209e-03 7.30912289e-04 1.68105300e-03
 1.14353571e-05 4.04314482e-05 1.99922248e-04 4.47530300e-04
 7.02494939e-04 7.43665184e-05 3.74880477e-04 1.88410328e-04
 0.00000000e+00 9.70704909e-04 4.22503626e-04 4.69788582e-04
 9.73660412e-04 1.07333422e-03 1.76341594e-04 2.00030322e-03
 2.09114787e-05 1.63236406e-05 6.10287559e-04 5.98942895e-04
 1.27300525e-04 9.096058

In [ ]:
RFAssesment_dict = {"Feature_Importance":RF.feature_importances_, "Feature_Name": selected_df.iloc[: , 7:-1].columns}
RFAssesment_df = pd.DataFrame(RFAssesment_dict)
print(RFAssesment_df)

ValueError: ignored

# Random Forest Model Evaluation

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_RFpred)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_RFpred)

In [ ]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_RFpred)

# Decision Tree Classifier 

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0)
for y
clf.fit(X_train, y_train)
y_clfpred = clf.predict(X_test)
prediction_dictclf = {"y_pred":y_clfpred, "y_test":y_test}
prediction_clfdf = pd.DataFrame(prediction_dictclf)
print(predictions_clfdf) 





In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_clfpred)
print(cm)
accuracy_score(y_test, y_clfpred)

In [ ]:
graph_x = X_train[:, 139]
plt.scatter(graph_x, y_train, color = 'red')

#plt.plot(X_train, regressor.predict(X_train), color = 'blue')
plt.title('Price Vs Predictors')
plt.xlabel('Predictors')
plt.ylabel('Price per night')
plt.show()
#(y_pred.reshape(len(y_pred),1)

##  Function that takes an input sample vector (one-hot encoded for locations) and gives us back the corresponding location



In [ ]:

def vec_to_name(vector, index_to_name_dict):

    for index, value in enumerate(vector):
        if value == 1:
            return index_to_name_dict[index]

neighbourhood_dictionary = {}
index_neighbourhood_dict = {}
for index, name in enumerate(neighbourhood_names):
    neighbourhood_dictionary[name] = index
    index_neighbourhood_dict[index] = name



## Visualization of the training results

In [ ]:
#index_neighbourhood_dict
#ax = fig.add_axes(len(X_svr))
location_svr = [vec_to_name(sample, ) for sample in X_svr]
fig=plt.figure() #Creates a new figure
ax1=fig.add_subplot(111);
line1 = ax1.plot(location_svr, y_svr)
plt.show() 

In [ ]:

indices_svr = [neighbourhood_dictionary[n] for n in location_svr]
plt.scatter(indices_svr, y_svr)
plt.show()

In [ ]:
print( index_neighbourhood_dict)

In [ ]:

plt.scatter(X_train, y_train, color = 'magenta')
plt.plot(X_test, classifier.predict(X_test), color = 'green')
plt.title('Support Vector Regression Model')
plt.xlabel('location')
plt.ylabel('peice per night')
plt.show()

# Mapping the listings

In [ ]:
from bokeh.io import output_file, output_notebook, show
from bokeh.models import (
  GMapPlot, GMapOptions, ColumnDataSource, Circle, LogColorMapper, BasicTicker, ColorBar,
    DataRange1d, PanTool, WheelZoomTool, BoxSelectTool
)
from bokeh.models.mappers import ColorMapper, LinearColorMapper
from bokeh.palettes import Viridis5


map_options = GMapOptions(lat=selected_df.iloc[: , 8].values, lng=selected_df.iloc[: , 9].values, map_type="roadmap", zoom=6)

plot = GMapPlot(
    x_range=DataRange1d(), y_range=DataRange1d(), map_options=map_options
)
plot.title.text = "Hey look! It's a scatter plot on a map!"

# For GMaps to function, Google requires you obtain and enable an API key:
#
#     https://developers.google.com/maps/documentation/javascript/get-api-key
#
# Replace the value below with your personal API key:
plot.api_key = "AIzaSyBYrbp34OohAHsX1cub8ZeHlMEFajv15fY"

source = ColumnDataSource(
    data=dict(
        lat=housing.latitude.tolist(),
        lon=housing.longitude.tolist(),
        size=housing.median_income.tolist(),
        color=housing.median_house_value.tolist()
    )
)
max_median_house_value = housing.loc[housing['median_house_value'].idxmax()]['median_house_value']
min_median_house_value = housing.loc[housing['median_house_value'].idxmin()]['median_house_value']

#color_mapper = CategoricalColorMapper(factors=['hi', 'lo'], palette=[RdBu3[2], RdBu3[0]])
#color_mapper = LogColorMapper(palette="Viridis5", low=min_median_house_value, high=max_median_house_value)
color_mapper = LinearColorMapper(palette=Viridis5)

circle = Circle(x="lon", y="lat", size="size", fill_color={'field': 'color', 'transform': color_mapper}, fill_alpha=0.5, line_color=None)
plot.add_glyph(source, circle)

color_bar = ColorBar(color_mapper=color_mapper, ticker=BasicTicker(),
                     label_standoff=12, border_line_color=None, location=(0,0))
plot.add_layout(color_bar, 'right')

plot.add_tools(PanTool(), WheelZoomTool(), BoxSelectTool())
#output_file("gmap_plot.html")
output_notebook()

show(plot)