In [30]:
import requests
import pandas as pd
from pandas import DataFrame 
%matplotlib inline
import matplotlib.pyplot as plt
import zipfile
import numpy as np
import io
import time
from numpy import nan
from pprint import pprint 
print("Import Successful")
#!wget https://www150.statcan.gc.ca/n1/tbl/csv/10100084-eng.zip
#!unzip 10100084-eng.zip

Import Successful


# Downloading the data

In [31]:



df = pd.read_csv("TorontoListings.csv")


# Data cleaning

In [32]:
df.describe()

id       host_id  neighbourhood_group      latitude  \
count  1.874600e+04  1.874600e+04                  0.0  18746.000000   
mean   2.673976e+07  1.087340e+08                  NaN     43.680717   
std    1.298332e+07  1.055992e+08                  NaN      0.048263   
min    1.419000e+03  1.565000e+03                  NaN     43.586710   
25%    1.634553e+07  2.049040e+07                  NaN     43.645170   
50%    2.775978e+07  6.787450e+07                  NaN     43.662815   
75%    3.853432e+07  1.823192e+08                  NaN     43.700153   
max    4.578971e+07  3.711952e+08                  NaN     43.836900   

          longitude         price  minimum_nights  number_of_reviews  \
count  18746.000000  18746.000000    18746.000000       18746.000000   
mean     -79.397420    135.468473       10.786568          26.635602   
std        0.064453    263.761517       36.913904          52.418576   
min      -79.634800     11.000000        1.000000           0.000000   
25%      -79.426310     61.000000        1.000000           1.000000   
50%      -79.397350     99.000000        2.000000           6.000000   
75%      -79.376860    150.000000        7.000000          27.000000   
max      -79.127810  13137.000000     1125.000000         828.000000   

       reviews_per_month  calculated_host_listings_count  availability_365  
count       14788.000000                    18746.000000      18746.000000  
mean            1.214266                        4.715246        125.690761  
std             1.597121                       10.354866        136.844548  
min             0.010000                        1.000000          0.000000  
25%             0.190000                        1.000000          0.000000  
50%             0.600000                        1.000000         83.000000  
75%             1.580000                        3.000000        252.000000  
max            15.440000                       88.000000        365.000000

From above, We can see there is a column which is empty, Hence, We drop empty, NAN data from the set. 

In [33]:

df.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group               float64
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

Since id and host_name, both are giving the same information, We keep one of them and We will do the same thing for name and coordination(lattitude+longitude), We will concatenate them into coulumn location

In [34]:
df['location'] = [', '.join(str(x) for x in y) for y in map(tuple, df[['latitude', 'longitude']].values)]
df.head(20)

id                                               name  host_id  \
0    1419                    Beautiful home in amazing area!     1565   
1    8077                 Downtown Harbourfront Private Room    22795   
2   12604                     Seaton Village Parlour Bedroom    48239   
3   23691                    Queen Bedroom close to downtown    93825   
4   26654  World Class downtown @CN Tower Theatre MTCC ga...   113345   
5   27423        Executive Studio Unit- Ideal for One Person   118124   
6   28160  Luxury, Safety, Affordability For Women Travel...    86838   
7   30931                 Downtown Toronto - Waterview Condo    22795   
8   40456  Downtown 2  Bdr.Apt with King Size Bed and Par...   174063   
9   41887                                     Great location   183071   
10  42892     Downtown 3 Beds 2 Baths @ Union & Harbourfront   187320   
11  43964  Bright entire 2-bedrm basement suite private e...   192364   
12  44452                       Yonge & Bloor Studio Skyline   195095   
13  45399                Fountain View Studio - Eaton center   195095   
14  45601                                   Marigold Gardens   188183   
15  45893                   Yonge & Bloor Lakeview Master BR   195095   
16  50110                        Yorkville one bedroom Condo   195095   
17  51616             Large room in trendy King Street West.   237587   
18  57483          Downtown 3 Beds 2 Baths @ Union & Harbour   187320   
19  64641                  Furnished Heritage Rooms Downtown   304551   

                host_name  neighbourhood_group  \
0               Alexandra                  NaN   
1          Kathie & Larry                  NaN   
2                    Rona                  NaN   
3           Yohan & Sarah                  NaN   
4                   Adela                  NaN   
5                   Brent                  NaN   
6                    Rita                  NaN   
7          Kathie & Larry                  NaN   
8                   Denis                  NaN   
9                    Kyle                  NaN   
10  Downtown Suite Living                  NaN   
11                  Mitra                  NaN   
12                 Urbano                  NaN   
13                 Urbano                  NaN   
14                  Simon                  NaN   
15                 Urbano                  NaN   
16                 Urbano                  NaN   
17                   John                  NaN   
18  Downtown Suite Living                  NaN   
19                 Kintoo                  NaN   

                        neighbourhood  latitude  longitude        room_type  \
0                     Little Portugal  43.64617  -79.42451  Entire home/apt   
1   Waterfront Communities-The Island  43.64105  -79.37628     Private room   
2                               Annex  43.66724  -79.41598     Private room   
3                Briar Hill-Belgravia  43.69602  -79.45468     Private room   
4   Waterfront Communities-The Island  43.64530  -79.38940  Entire home/apt   
5                   Greenwood-Coxwell  43.66890  -79.32592  Entire home/apt   
6                 Mount Pleasant West  43.70376  -79.39077  Entire home/apt   
7   Waterfront Communities-The Island  43.64151  -79.37643  Entire home/apt   
8                      South Parkdale  43.63532  -79.44049  Entire home/apt   
9                            Oakridge  43.69466  -79.28667  Entire home/apt   
10  Waterfront Communities-The Island  43.64451  -79.38185  Entire home/apt   
11                   Wexford/Maryvale  43.74948  -79.29147     Private room   
12                Rosedale-Moore Park  43.67185  -79.38583  Entire home/apt   
13              Church-Yonge Corridor  43.65972  -79.38172  Entire home/apt   
14                    South Riverdale  43.66274  -79.33096     Private room   
15                Rosedale-Moore Park  43.67105  -79.38481     Private room   
16              Church-Yonge Corridor  43.66899  -79.38548  Entire home/apt   


In [35]:
df.drop(['neighbourhood_group', 'name', 'host_name'], 1, inplace = True)
df.head()

id  host_id                      neighbourhood  latitude  longitude  \
0   1419     1565                    Little Portugal  43.64617  -79.42451   
1   8077    22795  Waterfront Communities-The Island  43.64105  -79.37628   
2  12604    48239                              Annex  43.66724  -79.41598   
3  23691    93825               Briar Hill-Belgravia  43.69602  -79.45468   
4  26654   113345  Waterfront Communities-The Island  43.64530  -79.38940   

         room_type  price  minimum_nights  number_of_reviews last_review  \
0  Entire home/apt    469               4                  7  2017-12-04   
1     Private room     98             180                169  2013-08-27   
2     Private room     66               1                  0         NaN   
3     Private room     70               1                217  2019-12-22   
4  Entire home/apt    125              21                 40  2020-03-20   

   reviews_per_month  calculated_host_listings_count  availability_365  \
0               0.11                               1                 0   
1               1.24                               2               365   
2                NaN                               1                 0   
3               1.72                               2               240   
4               0.34                               2               295   

                                 location  
0                     43.64617, -79.42451  
1            43.64105, -79.37628000000001  
2                     43.66724, -79.41598  
3  43.696020000000004, -79.45468000000001  
4                       43.6453, -79.3894

# Taking care of missing data

In [36]:
df = df[['id', 'host_id', 'neighbourhood', 'latitude', 'longitude', 'room_type','minimum_nights', 'number_of_reviews', 'last_review', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365', 'location', 'price']]

In [37]:
# replace '0' values with 'nan'
df[['number_of_reviews', 'availability_365']] = df[['number_of_reviews', 'availability_365']].replace(0, nan)
# count the number of nan values in each column
print(df.isnull().sum())

id                                   0
host_id                              0
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
minimum_nights                       0
number_of_reviews                 3958
last_review                       3958
reviews_per_month                 3958
calculated_host_listings_count       0
availability_365                  6641
location                             0
price                                0
dtype: int64


In [38]:
#conversion of the 'REF_DATE' from a string to a proper datetime object.
df['last_review'] = pd.to_datetime(df['last_review']) 
# fill missing values with mean column values
df.fillna(df.mean(), inplace=True)




<ipython-input-38-e19aafb883c7>:4: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  df.fillna(df.mean(), inplace=True)


# Encoding categorical Data

In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
X=df.iloc[: , 5:12].values
y=df.iloc[:, 13].values
one_hot = pd.get_dummies(df['room_type'])


In [40]:
one_hot_df = pd.concat([df, one_hot], axis=1)


In [41]:
one_hot_df = one_hot_df[['id', 'host_id', 'neighbourhood','minimum_nights', 'number_of_reviews',
       'calculated_host_listings_count', 'availability_365', 'reviews_per_month','latitude', 'longitude','Shared room', 'Entire home/apt',
       'Hotel room', 'Private room', 'price']]


In [42]:
#Encoding neighbourhood
one_hot = pd.get_dummies(df['neighbourhood'])


In [43]:
merged_df = pd.concat([one_hot_df, one_hot], axis=1)


In [44]:
merged_df["reviews_per_month"].mean()

1.2142662969974656

In [45]:
selected_df = merged_df[merged_df['reviews_per_month'] >= 1.2] 


In [46]:
def movecol(df, cols_to_move=[], ref_col='', place='After'):
    
    cols = df.columns.tolist()
    if place == 'After':
        seg1 = cols[:list(cols).index(ref_col) + 1]
        seg2 = cols_to_move
    if place == 'Before':
        seg1 = cols[:list(cols).index(ref_col)]
        seg2 = cols_to_move + [ref_col]
    
    seg1 = [i for i in seg1 if i not in seg2]
    seg3 = [i for i in cols if i not in seg1 + seg2]
    
    return(df[seg1 + seg2 + seg3])
selected_df = movecol(selected_df, 
             cols_to_move=['Yorkdale-Glen Park','price'], 
             ref_col='York University Heights',
             place='After')


# Definig dataset for the models

In the next lines, I am going to categorize the prices as low, affordable and expensive. Then then the model willl be trained sperately on each class.10 columns were selected to start with building our model and see how it works.

In [47]:
def priceRanker(val):
    if  val< 100:
        return 1
    elif 200 < val:
         return 2
    else :
         return 3

selected_df["categoryPrice"] = df["price"].apply(priceRanker)
   

In [48]:
selected_df

id    host_id                      neighbourhood  minimum_nights  \
1          8077      22795  Waterfront Communities-The Island             180   
2         12604      48239                              Annex               1   
3         23691      93825               Briar Hill-Belgravia               1   
9         41887     183071                           Oakridge              28   
10        42892     187320  Waterfront Communities-The Island              29   
...         ...        ...                                ...             ...   
18741  45785334    1023135                     Yonge-Eglinton              90   
18742  45786222  371188170                   Newtonbrook East              90   
18743  45786961  371195218                    Bayview Village               1   
18744  45789233  304805850             Corso Italia-Davenport               1   
18745  45789708  344709977                            Niagara               1   

       number_of_reviews  calculated_host_listings_count  availability_365  \
1             169.000000                               2        365.000000   
2              33.764606                               1        194.646758   
3             217.000000                               2        240.000000   
9              82.000000                               2        342.000000   
10             33.764606                              13        265.000000   
...                  ...                             ...               ...   
18741          33.764606                               1        344.000000   
18742          33.764606                               1        179.000000   
18743          33.764606                               1        194.646758   
18744          33.764606                               2         52.000000   
18745          33.764606                               1         33.000000   

       reviews_per_month  latitude  longitude  ...  Woburn  Woodbine Corridor  \
1               1.240000  43.64105  -79.37628  ...       0                  0   
2               1.214266  43.66724  -79.41598  ...       0                  0   
3               1.720000  43.69602  -79.45468  ...       0                  0   
9               1.740000  43.69466  -79.28667  ...       0                  0   
10              1.214266  43.64451  -79.38185  ...       0                  0   
...                  ...       ...        ...  ...     ...                ...   
18741           1.214266  43.70703  -79.40052  ...       0                  0   
18742           1.214266  43.79075  -79.39699  ...       0                  0   
18743           1.214266  43.76668  -79.37158  ...       0                  0   
18744           1.214266  43.67330  -79.44542  ...       0                  0   
18745           1.214266  43.64481  -79.40677  ...       0                  0   

       Woodbine-Lumsden  Wychwood  Yonge-Eglinton  Yonge-St.Clair  \
1                     0         0               0               0   
2                     0         0               0               0   
3                     0         0               0               0   
9                     0         0               0               0   
10                    0         0               0               0   
...                 ...       ...             ...             ...   
18741                 0         0               1               0   
18742                 0         0               0               0   
18743                 0         0               0               0   
18744                 0         0               0               0   
18745                 0         0               0               0   

       York University Heights  Yorkdale-Glen Park  price  categoryPrice  
1                            0                   0     98              1  
2                            0                   0     66              1  
3                            0                   0     70              1  
9

# SMOTE for imbalanced classification

if we go through the dataset after categorizing and applying the PriceRanker, it can be seen that there is an imblanced available data in mid range prices. To solve the problem we are going to deploy SMOTE.

In [86]:
!pip install  imbalanced-learn
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
#define dataset
X_df = selected_df.iloc[: , 7:-2]
X = X_df.values
y =selected_df.iloc[:, -1].values
#Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)
#SMOTE
sm = SMOTE()
X, y = sm.fit_sample(X_train, y_train)

# Decision Tree Cross Validation

For cross validation purposes, I am going to train 10% of our dataset.

now I need to define a new classifier to fit on our cross validation dataset. which I call it clf_cv

# Hyperparameter tuning for DT

In [87]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

acc_score_DT = []
best_score_DT = (0, -1)
best_clf_DT = None

for i in range(1,21) and for j in range(20,100):
    clf_DT = DecisionTreeClassifier(max_depth=i, n_estiator=j,random_state=0)
    clf_DT.fit(X_train, y_train)
    y_pred_DT=clf_DT.predict(X_test)
    
    curr_acc_DT = accuracy_score(y_test, y_pred_DT)
    acc_score_DT.append((i, j, curr_acc_DT))
    
    if curr_acc_DT > best_score_DT[0]:
        best_score_DT = (curr_acc_DT, i, j)
        best_clf_DT = clf_DT

print(best_clf_DT)
acc_score_DT

DecisionTreeClassifier(max_depth=4, random_state=0)


[(1, 0.615014436958614),
 (2, 0.615014436958614),
 (3, 0.6188642925890279),
 (4, 0.6386910490856593),
 (5, 0.6246390760346487),
 (6, 0.6300288739172281),
 (7, 0.6302213666987488),
 (8, 0.6306063522617902),
 (9, 0.6263715110683349),
 (10, 0.6148219441770933),
 (11, 0.6109720885466795),
 (12, 0.5942252165543792),
 (13, 0.5903753609239654),
 (14, 0.5894128970163619),
 (15, 0.5788257940327238),
 (16, 0.5757459095283927),
 (17, 0.5715110683349375),
 (18, 0.5782483156881617),
 (19, 0.5649663137632339),
 (20, 0.5684311838306063)]

## Matrix of confusion for Decision Tree cross validation

In [88]:
from sklearn.metrics import confusion_matrix
clf_DT_final = DecisionTreeClassifier(max_depth=4,random_state=0)
clf_DT_final.fit(X_train, y_train)
y_pred_DT=clf_DT_final.predict(X_test)
cm_DT = confusion_matrix(y_test, y_pred_DT)
print(cm_DT)
accuracy_score(y_test, y_pred_DT)

[[1737    2  817]
 [ 106    0  532]
 [ 416    4 1581]]


0.6386910490856593

# Random Forest Classification 


for random forest model we have to define the number of features that we are including in our model that for this case it is 147 ( total number of coulumns _ 9). 

In [93]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=1000, n_features=147,
                            n_informative=3, n_redundant=0,
                            random_state=0, shuffle=False)


# Hyperparameter Tuning for RF model

#For tuning I am going to train and fit the model with a different values for max_depth and n_estimator. I chose a range of 3 to 20 for max_depth and 20 to 100 for n_estimator.

In [94]:
acc_score_RF = []
best_score_RF = (0, -1)

for i in range(1,21) and for j in range(20,100):
    clf_RF = RandomForestClassifier(max_depth=i,n_estimator=j,random_state=0)
    clf_RF.fit(X_train, y_train)
    y_pred_RF=clf_RF.predict(X_test)
    
    curr_acc_RF = accuracy_score(y_test, y_pred_RF)
    acc_score_RF.append((i,j, curr_acc_RF))
    
    if curr_acc_RF > best_score_RF[0]:
        best_score_RF = (curr_acc_RF, i, j)
        best_clf_DT = clf_RF
        
print(best_clf_DT)
acc_score_RF


RandomForestClassifier(max_depth=11, random_state=0)


[(1, 0.5765158806544755),
 (2, 0.5871029836381135),
 (3, 0.5991337824831569),
 (4, 0.615014436958614),
 (5, 0.6260827718960539),
 (6, 0.6256015399422522),
 (7, 0.6299326275264677),
 (8, 0.6299326275264677),
 (9, 0.629451395572666),
 (10, 0.634744947064485),
 (11, 0.6371511068334937),
 (12, 0.634744947064485),
 (13, 0.6299326275264677),
 (14, 0.6323387872954764),
 (15, 0.634744947064485),
 (16, 0.6227141482194418),
 (17, 0.6275264677574591),
 (18, 0.6251203079884504),
 (19, 0.6256015399422522),
 (20, 0.6203079884504331)]

# now We need to creat a matrix of confusion for RF cross validation 

In [95]:
clf_RF = RandomForestClassifier(max_depth=11,random_state=0)
clf_RF.fit(X_train, y_train)
y_pred_RF=clf_RF.predict(X_test)
cm_RF= confusion_matrix(y_test, y_pred_RF)
print(cm_RF)
accuracy_score(y_test, y_pred_RF)

[[772   1 235]
 [ 73   0 183]
 [262   0 552]]


0.6371511068334937

# KNN Classifier

In [97]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)


# Hyperparameter tuning for KNN

##The only difference in terms of model tuning for KNN is we are changing the number of nearest numbers for a range from 4 to 20.

In [98]:
acc_score_knn = []
best_score_knn = (0, -1)

for i in range(1,21):
    neigh = KNeighborsClassifier(n_neighbors=i)
    neigh.fit(X_train, y_train)
    y_pred_knn=neigh.predict(X_test) 
  
  
    
    curr_acc_knn = accuracy_score(y_test, y_pred_knn)
    acc_score_knn.append((i, curr_acc_knn))
    
    if curr_acc_knn > best_score_knn[0]:
        best_score_knn = (curr_acc_knn, i)
        best_clf_DT = neigh
print(best_clf_DT)
acc_score_knn

KNeighborsClassifier(n_neighbors=20)


[(1, 0.5259865255052936),
 (2, 0.5235803657362849),
 (3, 0.5534167468719923),
 (4, 0.5625601539942252),
 (5, 0.5615976900866217),
 (6, 0.5808469682386911),
 (7, 0.5803657362848893),
 (8, 0.588065447545717),
 (9, 0.5909528392685275),
 (10, 0.5938402309913379),
 (11, 0.5856592877767084),
 (12, 0.591915303176131),
 (13, 0.5928777670837344),
 (14, 0.5933589990375361),
 (15, 0.5933589990375361),
 (16, 0.6034648700673725),
 (17, 0.5957651588065448),
 (18, 0.6044273339749759),
 (19, 0.6010587102983638),
 (20, 0.6068334937439847)]

# KNN confusion matrix

In [100]:
neigh = KNeighborsClassifier(n_neighbors=20)
neigh.fit(X_train, y_train)
y_pred_knn=neigh.predict(X_test) 
cm_knn= confusion_matrix(y_test, y_pred_knn)
print(cm_knn)
accuracy_score(y_test, y_pred_knn)

[[652   4 352]
 [ 58   6 192]
 [209   2 603]]


0.6068334937439847

# Random Forest Model

In [40]:

prediction_RFdict = {"y_pred":y_RFpred, "y_test":y_test}
predictions_RFdf = pd.DataFrame(prediction_RFdict)
print(predictions_RFdf) 



           y_pred  y_test
0      813.120000     169
1      152.160000     153
2      144.870000      73
3       44.300000      51
4       64.640000      51
5      182.050000     130
6       47.140000      50
7      131.730000      78
8      128.760000     146
9       78.700000      62
10     294.640000     150
11     140.210000     104
12     111.920000      99
13     144.950000     199
14      69.110000      38
15     172.880000     105
16     138.570000     225
17     168.470000     134
18     172.200000     199
19      95.380000     110
20      82.470000      85
21     139.400000      90
22      73.840000      54
23     121.910000     118
24     112.420000     110
25      94.250000     119
26     149.430000     100
27      62.180000      53
28     114.670000      70
29     122.520000      88
30     125.800000     113
31     155.390000     100
32      50.210000      53
33     249.310000     290
34     132.040000      45
35      85.370000      32
36      56.760000      61
37     132.4

In [41]:
print(best_clf_DT.feature_importances_)

[3.49485065e-02 5.52795588e-01 3.06983597e-01 8.47451382e-04
 2.08692245e-02 6.69762745e-05 1.60611662e-03 1.37117836e-05
 1.61847254e-04 2.06447380e-06 9.89014565e-03 1.75604721e-04
 7.64774336e-05 1.97518907e-03 6.16174719e-05 1.13805908e-02
 4.89340896e-04 6.48525444e-05 1.64691540e-05 1.14722246e-05
 6.71617090e-04 4.52839928e-05 9.91469591e-06 2.64478415e-04
 2.77154539e-05 1.52885236e-05 2.48097589e-03 1.03697932e-06
 9.95086850e-05 9.62443064e-06 3.04869725e-04 2.64413927e-05
 7.93294231e-03 3.59262738e-05 1.65911602e-05 9.71925765e-06
 1.04791309e-04 5.91318198e-04 1.37516522e-03 2.84050905e-04
 5.80193906e-05 1.23990155e-04 7.00465836e-05 4.15865868e-04
 3.19069582e-06 1.52873701e-06 1.14004002e-03 9.88832366e-05
 6.31753419e-04 9.56690785e-07 1.71196909e-05 4.49019815e-03
 1.54181666e-06 1.73608331e-04 4.01510772e-05 2.86900322e-04
 5.87600720e-04 2.66723472e-03 2.92284322e-06 1.02310046e-05
 2.62753399e-07 2.81513525e-06 1.93843441e-06 4.08217316e-05
 1.34861899e-05 1.482552

In [42]:
RFAssesment_dict = {"Feature_Importance":best_clf_DT.feature_importances_, "Feature_Name": X_df}
RFAssesment_df = pd.DataFrame(RFAssesment_dict)
print(RFAssesment_df)

     Feature_Importance                         Feature_Name
0          3.494851e-02                    reviews_per_month
1          5.527956e-01                             latitude
2          3.069836e-01                            longitude
3          8.474514e-04                          Shared room
4          2.086922e-02                      Entire home/apt
5          6.697627e-05                           Hotel room
6          1.606117e-03                         Private room
7          1.371178e-05                      Agincourt North
8          1.618473e-04         Agincourt South-Malvern West
9          2.064474e-06                            Alderwood
10         9.890146e-03                                Annex
11         1.756047e-04                    Banbury-Don Mills
12         7.647743e-05                       Bathurst Manor
13         1.975189e-03                  Bay Street Corridor
14         6.161747e-05                      Bayview Village
15         1.138059e-02 

# Random Forest Model Evaluation

In [43]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred_RF)

63186.99898229457

In [44]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_RF)

-0.07660328151077911

In [45]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred_RF)

80.77298512850129

##  Function that takes an input sample vector (one-hot encoded for locations) and gives us back the corresponding location



In [ ]:

def vec_to_name(vector, index_to_name_dict):

    for index, value in enumerate(vector):
        if value == 1:
            return index_to_name_dict[index]

neighbourhood_dictionary = {}
index_neighbourhood_dict = {}
for index, name in enumerate(neighbourhood_names):
    neighbourhood_dictionary[name] = index
    index_neighbourhood_dict[index] = name



## Visualization of the training results

In [ ]:
#index_neighbourhood_dict
#ax = fig.add_axes(len(X_svr))
location_svr = [vec_to_name(sample, ) for sample in X_svr]
fig=plt.figure() #Creates a new figure
ax1=fig.add_subplot(111);
line1 = ax1.plot(location_svr, y_svr)
plt.show() 

In [ ]:

indices_svr = [neighbourhood_dictionary[n] for n in location_svr]
plt.scatter(indices_svr, y_svr)
plt.show()

In [ ]:
print( index_neighbourhood_dict)

In [ ]:

plt.scatter(X_train, y_train, color = 'magenta')
plt.plot(X_test, classifier.predict(X_test), color = 'green')
plt.title('Support Vector Regression Model')
plt.xlabel('location')
plt.ylabel('peice per night')
plt.show()

# Mapping the listings

In [47]:
from bokeh.io import output_file, output_notebook, show
from bokeh.models import (
  GMapPlot, GMapOptions, ColumnDataSource, Circle, LogColorMapper, BasicTicker, ColorBar,
    DataRange1d, PanTool, WheelZoomTool, BoxSelectTool
)
from bokeh.models.mappers import ColorMapper, LinearColorMapper
from bokeh.palettes import Viridis5


map_options = GMapOptions(lat=selected_df.iloc[: , 8].values, lng=selected_df.iloc[: , 9].values, map_type="roadmap", zoom=6)

plot = GMapPlot(
    x_range=DataRange1d(), y_range=DataRange1d(), map_options=map_options
)
plot.title.text = "Hey look! It's a scatter plot on a map!"

# For GMaps to function, Google requires you obtain and enable an API key:
#
#     https://developers.google.com/maps/documentation/javascript/get-api-key
#
# Replace the value below with your personal API key:
plot.api_key = "AIzaSyBYrbp34OohAHsX1cub8ZeHlMEFajv15fY"

source = ColumnDataSource(
    data=dict(
        lat=housing.latitude.tolist(),
        lon=housing.longitude.tolist(),
        size=housing.median_income.tolist(),
        color=housing.median_house_value.tolist()
    )
)
max_median_house_value = housing.loc[housing['median_house_value'].idxmax()]['median_house_value']
min_median_house_value = housing.loc[housing['median_house_value'].idxmin()]['median_house_value']

#color_mapper = CategoricalColorMapper(factors=['hi', 'lo'], palette=[RdBu3[2], RdBu3[0]])
#color_mapper = LogColorMapper(palette="Viridis5", low=min_median_house_value, high=max_median_house_value)
color_mapper = LinearColorMapper(palette=Viridis5)

circle = Circle(x="lon", y="lat", size="size", fill_color={'field': 'color', 'transform': color_mapper}, fill_alpha=0.5, line_color=None)
plot.add_glyph(source, circle)

color_bar = ColorBar(color_mapper=color_mapper, ticker=BasicTicker(),
                     label_standoff=12, border_line_color=None, location=(0,0))
plot.add_layout(color_bar, 'right')

plot.add_tools(PanTool(), WheelZoomTool(), BoxSelectTool())
#output_file("gmap_plot.html")
output_notebook()

show(plot)

ValueError: expected a value of type Real, got [43.64105 43.66724 43.69602 ... 43.76668 43.6733  43.64481] of type ndarray